zeus-transaction-manager:
  api:
    version: 1.0.0
server:
  port: 8095
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: zeus-transaction-manager-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  profiles:
    active: clean, local
logging:
  file:
    name: logs/local/transaction-manager.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
