zeus-transaction-manager:
  api:
    version: 1.0.0
server:
  port: 8095
spring:
  profiles:
    active: clean, local
logging:
  file:
    name: logs/local/transaction-manager.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
