zeus-transaction-manager:
  api:
    version: 1.0.0
url:
  host:
    plan-catalog: http://localhost:9002/api/v1
    mms: http://localhost:8084/api/v1
server:
  port: 8095
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/transactionmanagerdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: transactionmanageradmin
    password: password
  flyway:
    user: transactionmanageradmin
    password: password
    clean-disabled: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: zeus-transaction-manager-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  profiles:
    active: clean, local
logging:
  file:
    name: logs/local/transaction-manager.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
